---
title: "Praca domowa nr 4"
author: "Marceli Korbin"
date: "27 kwietnia 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

## Wstęp

Dla dwóch zbiorów danych stroimy parametry algorytmu SVM.

## Przygotowanie

```{r pressure, echo=FALSE}
library(e1071)
library(DALEX)
library(dplyr)
library(mlr)
# potrzebne biblioteki
heart <- read.csv("heart.csv")
data(apartments, package="DALEX")
# zbiory danych apartments i heart

trainc1 <- sample(1:nrow(apartments), 0.7*nrow(apartments))
train1 <- apartments[trainc1,]
test1 <- apartments[-trainc1,]
trainc2 <- sample(1:nrow(heart), 0.7*nrow(heart))
train2 <- heart[trainc2,]
test2 <- heart[-trainc2,]
# podział danych na zbiory treningowe i testowe
train1bv <- train1
# do sprawdzenia skalowania
```

### Zbiór "apartments"

```{r svm1}
task1 <- makeClassifTask(data=train1, target="district")
learner <- makeLearner("classif.svm",
                       par.vals=list(kernel="radial", cost=100),
                       predict.type="response")
model1 <- train(learner, task1)
all(train1==train1bv)
# TRUE - dane się nie zmieniły, więc dla takiej implementacji skalowanie w miejscu nie zachodzi
pred1 <- predict(model1, newdata=test1)

cv <- makeResampleDesc("CV", iter=6)
parSet <- makeParamSet(
  makeIntegerParam("cost", lower=10, upper=300),
  makeDiscreteParam("kernel", values=c("linear", "polynomial", "radial", "sigmoid")),
  makeIntegerParam("degree", lower=2, upper=10),
  makeNumericParam("gamma", lower=1, upper=10, trafo=function(x) 1/x)
)

# stroimy parametry
ctrlR <- makeTuneControlRandom(maxit = 30)
resR <- tuneParams(learner, task=task1, resampling=cv,
                   par.set=parSet, control=ctrlR, measures=acc)
modelR <- train(resR$learner, task1)
pred10 <- predict(modelR, newdata=test1)
measureACC(pred10$data$response, pred10$data$truth)
```

W linijce "[Tune] Result" można odczytać optymalne parametry, dla których wybrana miara wyszła najwyższa.

### Zbiór "heart"

```{r svm2}
task2 <- makeClassifTask(data=train2, target="num")
renrael <- makeLearner("classif.svm",
                       par.vals=list(kernel="radial", cost=100),
                       predict.type="response")
model2 <- train(renrael, task2)
pred2 <- predict(model2, newdata=test2)

cv2 <- makeResampleDesc("CV", iter=6)
parSet2 <- makeParamSet(
  makeIntegerParam("cost", lower=10, upper=300),
  makeDiscreteParam("kernel", values=c("linear", "polynomial", "radial", "sigmoid")),
  makeIntegerParam("degree", lower=2, upper=10),
  makeNumericParam("gamma", lower=1, upper=10, trafo=function(x) 1/x)
)

# stroimy parametry
ctrlS <- makeTuneControlRandom(maxit = 30)
resS <- tuneParams(learner, task=task2, resampling=cv2,
                   par.set=parSet2, control=ctrlS, measures=f1)
modelS <- train(resS$learner, task2)
pred20 <- predict(modelS, newdata=test2)
measureF1(pred20$data$response, pred20$data$truth, "0")
```